{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[[]]},"sections":[],"metadata":{"title":"NoveoFlowersProvider","roleHeading":"Framework","role":"collection","modules":[{"name":"NoveoFlowersProvider"}],"externalID":"NoveoFlowersProvider","symbolKind":"module"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider"},"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/FlowersItemsProvider"]},{"identifiers":["doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/ItemsProvider"],"anchor":"Protocols","generated":true,"title":"Protocols"},{"title":"Structures","generated":true,"identifiers":["doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/Category","doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/Item"],"anchor":"Structures"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/noveoflowersprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/noveoflowersprovider"]}],"references":{"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider/ItemsProvider":{"type":"topic","url":"\/documentation\/noveoflowersprovider\/itemsprovider","kind":"symbol","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/ItemsProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ItemsProvider"}],"navigatorTitle":[{"text":"ItemsProvider","kind":"identifier"}],"title":"ItemsProvider","role":"symbol","abstract":[{"text":"A protocol defining operations for managing categories and items.","type":"text"}]},"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider/Category":{"type":"topic","url":"\/documentation\/noveoflowersprovider\/category","abstract":[{"text":"A model representing a product category.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Category","kind":"identifier"}],"kind":"symbol","title":"Category","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/Category","role":"symbol","navigatorTitle":[{"text":"Category","kind":"identifier"}]},"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider/NoveoFlowersProviderVersionString":{"role":"symbol","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/NoveoFlowersProviderVersionString","kind":"symbol","type":"topic","url":"\/documentation\/noveoflowersprovider\/noveoflowersproviderversionstring","fragments":[{"text":"NoveoFlowersProviderVersionString","kind":"identifier"}],"title":"NoveoFlowersProviderVersionString","abstract":[{"type":"text","text":"Project version string for NoveoFlowersProvider."}]},"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider/NoveoFlowersProviderVersionNumber":{"abstract":[{"text":"Project version number for NoveoFlowersProvider.","type":"text"}],"role":"symbol","title":"NoveoFlowersProviderVersionNumber","type":"topic","url":"\/documentation\/noveoflowersprovider\/noveoflowersproviderversionnumber","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/NoveoFlowersProviderVersionNumber","kind":"symbol","fragments":[{"text":"NoveoFlowersProviderVersionNumber","kind":"identifier"}]},"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider":{"kind":"symbol","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider","url":"\/documentation\/noveoflowersprovider","role":"collection","type":"topic","title":"NoveoFlowersProvider","abstract":[]},"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider/Item":{"kind":"symbol","navigatorTitle":[{"text":"Item","kind":"identifier"}],"abstract":[{"text":"A model representing a product or service item.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/noveoflowersprovider\/item","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/Item","title":"Item","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Item","kind":"identifier"}]},"doc://com.noveogroup.ios.NoveoFlowersProvider/documentation/NoveoFlowersProvider/FlowersItemsProvider":{"abstract":[{"text":"A test implementation of the ","type":"text"},{"type":"codeVoice","code":"ItemsProvider"},{"type":"text","text":" protocol that simulates loading items and categories."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/FlowersItemsProvider","url":"\/documentation\/noveoflowersprovider\/flowersitemsprovider","navigatorTitle":[{"kind":"identifier","text":"FlowersItemsProvider"}],"type":"topic","title":"FlowersItemsProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FlowersItemsProvider","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/NoveoFlowersProviderVersionNumber","doc:\/\/com.noveogroup.ios.NoveoFlowersProvider\/documentation\/NoveoFlowersProvider\/NoveoFlowersProviderVersionString"]}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}